name: Create SQL Server Table (Test)

on:
  workflow_dispatch:

jobs:
  create-table:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install sqlcmd
        run: choco install sqlcmd -y

      - name: Create table in SQL Server
        run: |
          sqlcmd `
            -S "${{ secrets.DB_SERVER }}" `
            -U sa `
            -P "Satish@02" `
            -d master `
            -Q "IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='master')
                BEGIN
                  CREATE TABLE TestTable_a (
                    Id INT IDENTITY(1,1) PRIMARY KEY,
                    Name NVARCHAR(100),
                    CreatedDate DATETIME DEFAULT GETDATE()
                  )
                END"
