name: Flyway Migration

on:
  push:
    branches: 
      - main

jobs:
  flyway-migration:
    runs-on: windows-latest   # MUST be Windows if connecting to your local/on-prem SQL for test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Flyway
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.9.1/flyway-commandline-10.9.1-windows-x64.zip -o flyway.zip
          tar -xf flyway.zip
          ren flyway-10.9.1 flyway

      - name: Run Flyway Migrations
        env:
          FLYWAY_URL: jdbc:sqlserver://192.168.0.88:54608;databaseName=master;encrypt=false
          FLYWAY_USER: sa
          FLYWAY_PASSWORD: MMSPhW110

        run: |
          flyway\flyway migrate `
            -url="%FLYWAY_URL%" `
            -user="%FLYWAY_USER%" `
            -password="%FLYWAY_PASSWORD%" `
            -locations=filesystem:./sql


