name: Create SQL Server DB & Table (From SQL File)

on:
  workflow_dispatch:

jobs:
  create-table:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install sqlcmd
        run: choco install sqlcmd -y
        
# Step 1: Create Database
      - name: Create Database
        shell: pwsh
        run: |
          sqlcmd `
            -S "${{ secrets.DB_SERVER }}" `
            -U "${{ secrets.DB_USER }}" `
            -P "${{ secrets.DB_PASSWORD }}" `
            -d  `
            -i "sql/01_create_database.sql"

# Step 2: Create Tables
      - name: Create Tables
        shell: pwsh
        run: |
          sqlcmd `
            -S "${{ secrets.DB_SERVER }}" `
            -U "${{ secrets.DB_USER }}" `
            -P "${{ secrets.DB_PASSWORD }}" `
            -d  `
            -i "sql/02_create_tables.sql"
